player:
  # - name: "gpt-oss-120b"
  #   base_url: "http://14.103.241.208:28888/v1/"
  #   model: "openai/gpt-oss-120b"
  # - name: "gpt-oss-20b-medium"
  #   base_url: "http://14.103.241.208:27777/v1/"
  #   model: "openai/gpt-oss-20b"
  #   reasoning_effort: "medium"
  - name: "gpt-oss-20b-low"
    base_url: "http://14.103.241.208:27777/v1/"
    model: "openai/gpt-oss-20b"
    reasoning_effort: "low"
  - name: "Human"
    player_type: "HumanPlayer"
